stages:
  - test
  - build
  - deploy

test:
  stage: test
  only:
    - develop
  script:
    - npm set progress=true
    - node_modules/eslint/bin/eslint src/**/*.js

deploy_job:
  stage: deploy
  script:
  - make deploy
  when: manual
